"""Shared output module: converts a voice profile dict to 4 markdown files.

Called by all setup scripts. Analysis logic stays in each script —
this module only handles serialization from profile dict → voice/ markdown.
"""
import json
from datetime import datetime
from pathlib import Path


def write_voice_markdown(profile, out_dir, source_label="auto-setup"):
    """Write 4 voice markdown files from a profile dict.

    Args:
        profile: dict from build_voice_profile() / build_profile()
        out_dir: Path to voice/ directory (created if missing)
        source_label: label for changelog entry
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    _write_profile_md(profile, out_dir / "profile.md")
    _write_patterns_md(profile, out_dir / "patterns.md")
    _write_marketing_voice_md(profile, out_dir / "marketing-voice.md")
    _write_changelog_md(out_dir / "changelog.md", source_label)

    return out_dir


def _write_profile_md(p, path):
    """voice/profile.md — how this person writes."""
    lang = p.get("language", {}).get("primary", "en")
    tone = p.get("tone", {})
    vocab = p.get("personal_vocabulary", {})

    # Derive register from tone
    summary = tone.get("summary", "")
    if "casual" in summary.lower():
        register = "casual"
    elif "formal" in summary.lower():
        register = "formal"
    else:
        register = "mixed"

    # Build signature patterns from tone.do
    tone_do = tone.get("do", [])
    pattern_rows = []
    for item in tone_do:
        pattern_rows.append(f"| {item} | tone rule | from analysis | low |")

    # Anti-patterns from banned phrases
    banned = vocab.get("phrases_banned", [])
    if not banned:
        banned = vocab.get("phrases_you_use_freely", [])
        banned = []  # if no banned, leave empty
    banned_lines = "\n".join(f"- {phrase}" for phrase in banned) if banned else "- [none detected yet]"

    # Use-freely phrases
    use_freely = vocab.get("phrases_you_use_freely", vocab.get("phrases_to_use_freely", []))
    use_freely_str = ", ".join(use_freely[:15]) if use_freely else "[none detected yet]"

    # Avoid phrases from tone.dont
    tone_dont = tone.get("dont", [])
    avoid_str = ", ".join(tone_dont[:10]) if tone_dont else "[none detected yet]"

    # Build evaluator checklist
    must_have = []
    for item in tone_do[:3]:
        must_have.append(f"- [ ] {item}")

    enhancers = []
    for item in tone_do[3:]:
        enhancers.append(f"- [ ] {item}")

    never_use = []
    for phrase in banned[:5]:
        never_use.append(f"- [ ] {phrase}")

    lines = f"""# Voice Profile

> Generated by koko-ship voice setup.
> Updated via voice evolution loop (user approves all changes).

## Identity

**Language:** {lang}
**Register:** {register}
**Voice summary:** {summary}

## Signature Patterns

Patterns that should appear in most posts.

| Pattern | Description | Example | Force risk |
|---------|-------------|---------|------------|
{chr(10).join(pattern_rows) if pattern_rows else "| [none extracted yet] | | | |"}

## Anti-Patterns (Never-Use)

Any of these in a draft = auto-fail.

{banned_lines}

## Vocabulary Markers

**Use freely:** {use_freely_str}
**Avoid:** {avoid_str}

## Sentence Rhythm

{_derive_rhythm(p)}

## Emotional Expression

[Will be enriched as more writing samples are analyzed and edits are captured.]

## Evaluator Checklist

### Must-have (check every post)
{chr(10).join(must_have) if must_have else "- [ ] [will be populated as voice evolves]"}

### Enhancers (nice to have)
{chr(10).join(enhancers) if enhancers else "- [ ] [will be populated as voice evolves]"}

### Never-use (auto-fail)
{chr(10).join(never_use) if never_use else "- [ ] [will be populated as voice evolves]"}

### Learned patterns (added via voice evolution)
_Empty until 5+ posts with edits or explicit user direction._
"""
    path.write_text(lines.strip() + "\n")


def _derive_rhythm(p):
    structure = p.get("structure", {})
    length = p.get("length", {})
    lb = structure.get("line_breaks", {})

    parts = []
    if lb.get("use") == "aggressive":
        parts.append("Aggressive line breaks — each line is one beat.")
    target = length.get("target_chars", [180, 260])
    if target:
        parts.append(f"Target length: {target[0]}-{target[1]} characters.")
    lines_range = length.get("optimal_lines", [3, 6])
    if lines_range:
        parts.append(f"Optimal lines: {lines_range[0]}-{lines_range[1]}.")

    return " ".join(parts) if parts else "[Will be derived from writing samples.]"


def _write_patterns_md(p, path):
    """voice/patterns.md — how this person thinks."""
    # This is thin on first auto-setup — enriched over time
    directives = p.get("directive_counts", {}) if "directive_counts" in p else {}
    source = p.get("$built_from", "unknown")

    # Derive approach from directive counts if available
    approach = "[Will be enriched as more data is ingested.]"
    if directives:
        decisive = directives.get("decisive", 0)
        exploration = directives.get("exploration", 0)
        if decisive > exploration:
            approach = "Action-first. Decides quickly, iterates after. Uses short directive commands."
        elif exploration > decisive:
            approach = "Question-first. Explores before deciding. Asks why before how."
        else:
            approach = "Balanced. Alternates between exploration and decisive action."

    lines = f"""# Thinking Patterns

> How this person thinks — not what they write, but how they approach problems.
> Used for moment selection and angle choice during post generation.
> Source: {source}

## Problem Approach

{approach}

## First Reactions

[How they react to success, failure, surprise — captured from session behavior over time.]

## How They Argue

[How they push back, express disagreement, defend positions. Enriched over time.]

## What Excites Them

[Topics, outcomes, or situations that generate energy in their writing.]

## What Frustrates Them

[Patterns, situations, or outcomes that trigger frustration signals.]

## Framing Style

[How they frame ideas — metaphors, binaries, questions, stories. Derived from writing samples.]

## Vocabulary Shifts

[How their language changes across domains or contexts. Tracked over time.]
"""
    path.write_text(lines.strip() + "\n")


def _write_marketing_voice_md(p, path):
    """voice/marketing-voice.md — the publishable filter."""
    length = p.get("length", {})
    hooks = p.get("hooks", {})
    emoji = p.get("emoji", {})
    hashtags = p.get("hashtags", {})
    security = p.get("security_filter", {})

    target = length.get("target_chars", [180, 260])
    max_chars = length.get("max_chars", 280)
    opt_lines = length.get("optimal_lines", [3, 6])

    preferred_hooks = hooks.get("preferred_patterns", [])
    avoid_hooks = hooks.get("avoid_patterns", [])

    emoji_default = emoji.get("current_default", "none")
    emoji_max = emoji.get("max_per_post", 0)
    emoji_avoid = emoji.get("avoid", [])

    ht_generic_avoid = hashtags.get("generic_to_avoid", [])

    security_remove = security.get("remove", [])
    security_keep = security.get("keep", [])

    lines = f"""# Marketing Voice

> What's publishable vs private. Post formatting rules.
> Read by writer (output formatting) and QA (privacy check).

## What's Publishable

- Building process, struggles, discoveries
- Specific numbers and outcomes
- Honest emotional beats (doubt, surprise, frustration)
- Tech stack and tool choices
- Design decisions and trade-offs

## Keep Private

- Other people's names or details (unless they're public figures)
- Internal team dynamics
- Financial specifics beyond what's publicly shared
- Anything that feels too raw or unprocessed

## Post Characteristics

**Format:** single tweet (threads only when explicitly asked)
**Length:** {target[0]}-{target[1]} characters (max {max_chars})
**Lines:** {opt_lines[0]}-{opt_lines[1]} lines
**Line breaks:** aggressive — each line is one beat
**Emoji:** default {emoji_default}, max {emoji_max} per post
**Emoji to avoid:** {', '.join(emoji_avoid) if emoji_avoid else 'none specified'}
**Hashtag:** exactly one branded hashtag, trailing line, never generic
**Generic hashtags to avoid:** {', '.join(ht_generic_avoid) if ht_generic_avoid else 'none specified'}

## Hook Preferences

**Preferred patterns:** {', '.join(preferred_hooks) if preferred_hooks else 'any that stop the scroll'}
**Avoid:** {', '.join(avoid_hooks) if avoid_hooks else 'none specified'}

## Content Angles

- What broke and how it got fixed (struggle → resolution)
- Unexpected discoveries (tried X, learned Y)
- Specific numbers that changed (users, metrics, streaks)
- Real questions whose answers would change what you build
- Honest emotional beats (not performed)

## Security Filter

**Always remove:**
{chr(10).join(f'- {item}' for item in security_remove) if security_remove else '- API keys, secrets, PII'}

**Always keep:**
{chr(10).join(f'- {item}' for item in security_keep) if security_keep else '- Tech stack, architecture decisions'}
"""
    path.write_text(lines.strip() + "\n")


def _write_changelog_md(path, source_label):
    """voice/changelog.md — voice evolution tracker."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = f"""# Voice Changelog

> Every voice profile update is logged here.
> Each entry has: date, what changed, source, which patterns affected.

## {now} — initial voice setup

- **Source:** {source_label}
- **What:** created initial voice profile from {source_label}
- **Patterns affected:** all (first setup)
"""
    path.write_text(lines.strip() + "\n")


def migrate_json_to_markdown(json_path, out_dir):
    """Migrate an existing .bip-voice.json to voice/ markdown format.

    Returns the out_dir Path if successful, None if the JSON couldn't be read.
    """
    json_path = Path(json_path)
    if not json_path.exists():
        return None

    try:
        profile = json.loads(json_path.read_text())
    except (json.JSONDecodeError, OSError):
        return None

    return write_voice_markdown(profile, out_dir, source_label="migrated-from-json")
